# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Player_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 459)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(40, 20, 121, 31))
        self.name.setObjectName("name")
        self.notice = QtWidgets.QLabel(self.centralwidget)
        self.notice.setGeometry(QtCore.QRect(390, 50, 261, 31))
        self.notice.setObjectName("notice")
        self.start = QtWidgets.QLabel(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(20, 290, 211, 21))
        self.start.setObjectName("start")
        self.end = QtWidgets.QLabel(self.centralwidget)
        self.end.setGeometry(QtCore.QRect(20, 360, 211, 21))
        self.end.setObjectName("end")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(390, 20, 251, 31))
        self.label_6.setObjectName("label_6")
        self.btn_go = QtWidgets.QPushButton(self.centralwidget)
        self.btn_go.setGeometry(QtCore.QRect(520, 300, 121, 81))
        self.btn_go.setObjectName("btn_go")
        self.txt_name_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_name_1.setGeometry(QtCore.QRect(240, 20, 131, 31))
        self.txt_name_1.setDocumentTitle("")
        self.txt_name_1.setObjectName("txt_name_1")
        self.txt_end = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_end.setGeometry(QtCore.QRect(240, 350, 131, 31))
        self.txt_end.setObjectName("txt_end")
        self.txt_start = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_start.setGeometry(QtCore.QRect(240, 280, 131, 31))
        self.txt_start.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txt_start.setObjectName("txt_start")
        self.txt_id = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_id.setGeometry(QtCore.QRect(510, 190, 131, 31))
        self.txt_id.setDocumentTitle("")
        self.txt_id.setObjectName("txt_id")
        self.name_2 = QtWidgets.QLabel(self.centralwidget)
        self.name_2.setGeometry(QtCore.QRect(470, 190, 31, 31))
        self.name_2.setObjectName("name_2")
        self.name_3 = QtWidgets.QLabel(self.centralwidget)
        self.name_3.setGeometry(QtCore.QRect(460, 230, 31, 31))
        self.name_3.setObjectName("name_3")
        self.txt_name_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_name_2.setGeometry(QtCore.QRect(240, 60, 131, 31))
        self.txt_name_2.setDocumentTitle("")
        self.txt_name_2.setObjectName("txt_name_2")
        self.txt_name_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_name_3.setGeometry(QtCore.QRect(240, 100, 131, 31))
        self.txt_name_3.setDocumentTitle("")
        self.txt_name_3.setObjectName("txt_name_3")
        self.txt_name_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_name_4.setGeometry(QtCore.QRect(240, 140, 131, 31))
        self.txt_name_4.setDocumentTitle("")
        self.txt_name_4.setObjectName("txt_name_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 16, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 70, 16, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 110, 16, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 150, 16, 17))
        self.label_4.setObjectName("label_4")
        self.txt_pw = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_pw.setGeometry(QtCore.QRect(510, 230, 131, 31))
        self.txt_pw.setObjectName("txt_pw")
        self.txt_pw.setEchoMode(QLineEdit.Password)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setText(_translate("MainWindow", "과목명  :"))
        self.notice.setText(_translate("MainWindow", "(우상단의 Englich(en)로  확인)"))
        self.start.setText(_translate("MainWindow", "틀고싶은 영상 주차 시작 :"))
        self.end.setText(_translate("MainWindow", "틀고싶은 영상 주차 끝 :"))
        self.label_6.setText(_translate("MainWindow", "사이트가 영어면"))
        self.btn_go.setText(_translate("MainWindow", "do macro"))
        self.name_2.setText(_translate("MainWindow", "ID :"))
        self.name_3.setText(_translate("MainWindow", "PW :"))
        self.label.setText(_translate("MainWindow", "1)"))
        self.label_2.setText(_translate("MainWindow", "2)"))
        self.label_3.setText(_translate("MainWindow", "3)"))
        self.label_4.setText(_translate("MainWindow", "4)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

